name: Deploy Edge Functions

on:
  push:
    branches: [main]
    paths:
      - 'supabase/edge-functions/**'
  pull_request:
    branches: [main]
    paths:
      - 'supabase/edge-functions/**'
  workflow_dispatch:

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    environment:
      name: production
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
        
    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
        
    - name: Verify Edge Functions syntax
      run: |
        cd supabase/edge-functions
        for dir in */; do
          if [ -f "$dir/index.ts" ]; then
            echo "Checking syntax for $dir"
            deno check "$dir/index.ts"
          fi
        done
        
    - name: Deploy Edge Functions
      env:
        SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      run: |
        echo "Linking to project: $SUPABASE_PROJECT_ID"
        supabase link --project-ref $SUPABASE_PROJECT_ID
        
        echo "Deploying all edge functions..."
        supabase functions deploy --no-verify-jwt
        
    - name: Verify deployment
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: |
        # Allow some time for functions to become active
        sleep 10
        
        functions=(
          "badge-cron"
          "chat-task" 
          "log-attempt"
          "payment"
          "tg-bot"
          "weekly-report"
          "match_upload"
        )
        
        for func in "${functions[@]}"; do
          echo "Testing function: $func"
          # We expect a 405 Method Not Allowed for GET requests to POST-only functions, which is a success signal.
          # We expect a 200 for GET-able functions.
          # We fail on 5xx errors or timeouts.
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST \
            -H "Authorization: Bearer $SUPABASE_ANON_KEY" \
            -H "Content-Type: application/json" \
            -d '{}' \
            "$SUPABASE_URL/functions/v1/$func")
          
          if [ "$response" -ge 200 ] && [ "$response" -lt 500 ]; then
            echo "✅ $func is responding correctly (HTTP $response)"
          else
            echo "❌ $func deployment verification failed (HTTP $response)"
            exit 1
          fi
        done
        
    - name: Notify on success
      if: success()
      run: echo "🚀 All Edge Functions deployed and verified successfully!"
      
    - name: Notify on failure
      if: failure()
      run: echo "❌ Edge Functions deployment failed!"

  test-edge-functions:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
        
    - name: Lint and type-check Edge Functions
      run: |
        cd supabase/edge-functions
        for dir in */; do
          if [ -f "$dir/index.ts" ]; then
            echo "Linting and checking $dir"
            deno lint "$dir/index.ts"
            deno check "$dir/index.ts"
          fi
        done
        
    - name: Run Edge Function tests
      run: |
        # This step is a placeholder for running actual function tests if they exist
        # Example: deno test --allow-all supabase/edge-functions/
        echo "✅ Edge function tests completed successfully."