name: Embed nightly
on:
  schedule: [{ cron: "0 2 * * *" }]
jobs:
  embed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: 3.11 }
      - run: pip install -r scripts/requirements.txt
      - run: python scripts/embed_chunks.py
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
