name: Embed nightly
on:
  schedule: [{ cron: "0 2 * * *" }]
  workflow_dispatch: # Allow manual trigger

jobs:
  embed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r scripts/requirements.txt
      
      - name: Run embedding script
        run: python scripts/embed_chunks.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
      - name: Report results
        run: |
          echo "✅ Embedding job completed successfully"
          echo "📊 Check Supabase logs for detailed results"
